config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Photo app Charge',
    currency: 'usd',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photoapp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
<!-- begin navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if current_user %>
                <li class="col-md-8 user-name">
                <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe,edit_user_registration_path, title: 'Edit Profile' %>
                </li>
                <li class="col-md-1"> </li>
                <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path,class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
            <% else %>
              <li class="col-md-4 pull-right">
              <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
              </li>
              <li class="col-md-4 pull-right">
              <%= link_to('Sign Up', new_user_registration_path, class: 'btn btn-success', title: 'Sign Up') %>
              </li>
            <% end %>
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
  <!-- end navbar -->
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% if current_user %>
  <h3>Welcome: <%= current_user.email %></h3>
<% else %>
	<div>
	  <div class="jumbotron">
	  	<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	    <h2>Welcome to the Photo Management App!</h2>
	    <p class="lead">
	      You'll love managing your Photos with our application. Sign up!
	    </p>
	  </div>

		<div class="container">
		  <div class="card-deck mb-3 text-center">
		    <div class="card mb-4 shadow-sm">
		      <div class="card-header">
		        <h4 class="my-0 font-weight-normal">Free</h4>
		      </div>
		      <div class="card-body">
		        <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
		        <ul class="list-unstyled mt-3 mb-4">
		          <li>10 users included</li>
		          <li>2 GB of storage</li>
		          <li>Email support</li>
		          <li>Help center access</li>
		        </ul>
		        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-block btn-primary sign-up' %>
		      </div>
		    </div>
		    <div class="card mb-4 shadow-sm">
		      <div class="card-header">
		        <h4 class="my-0 font-weight-normal">Pro</h4>
		      </div>
		      <div class="card-body">
		        <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
		        <ul class="list-unstyled mt-3 mb-4">
		          <li>20 users included</li>
		          <li>10 GB of storage</li>
		          <li>Priority email support</li>
		          <li>Help center access</li>
		        </ul>
		        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-block btn-primary sign-up' %>
		      </div>
		    </div>
		    <div class="card mb-4 shadow-sm">
		      <div class="card-header">
		        <h4 class="my-0 font-weight-normal">Enterprise</h4>
		      </div>
		      <div class="card-body">
		        <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
		        <ul class="list-unstyled mt-3 mb-4">
		          <li>30 users included</li>
		          <li>15 GB of storage</li>
		          <li>Phone and email support</li>
		          <li>Help center access</li>
		        </ul>
		        <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
		      </div>
		    </div>
		  </div>
		</div>
	</div>
<% end %>